spring.application.name: scarlett_notification_service
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scarlett_notification
    username: postgres
    password: postgres
  jpa:
    properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update